<a href="https://colab.research.google.com/github/1994shuklaanand/International-Debt-Statistics-Analysis/blob/main/international_debt_statistics_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [15]:
allcountry = pd.read_csv("/content/IDS_ALLCountries_Data.csv")
countryseriesmetadata = pd.read_csv("/content/IDS_Country-SeriesMetaData.csv", encoding='latin-1')
countrymetadata = pd.read_csv("/content/IDS_CountryMetaData.csv", encoding='latin-1')
footnotes = pd.read_csv("/content/IDS_Footnotes.csv", encoding='latin-1')
seriesmetadata = pd.read_csv("/content/IDS_SeriesMetaData.csv", encoding='latin-1')

In [16]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Creating a Helper

In [17]:
# Printing Top 5 Rows
def head(n):
  return n.head()

# Printing Last 5 Rows
def tail(n):
  return n.tail()

# Printing Random 10 Rows
def sample(n):
  return n.sample(10)

# Printing Total Number of Rows and Columns
def shape(n):
  return n.shape

# Priniting Dataset Information
def info(n):
  return n.info()

# Priniting Dataset Columns Name
def columns(n):
  return n.columns

# Priniting Dataset Statistical Information
def describe(n):
  return n.describe()

# Printing Top 5 Rows

In [18]:
head(allcountry)

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
0,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.DPPG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.2500,8.0833,9.9575,0.0,7.8333,0.0,0.0,0.0,29.8333,0.0,0.0,19.8356,0.0,17.9041,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.OFFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.2500,8.0833,9.9575,0.0,7.8333,0.0,0.0,0.0,29.8333,0.0,0.0,19.8356,0.0,17.9041,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.PRVT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.DPPG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.6176,43.0248,58.0061,0.0,21.2119,0.0,0.0,0.0,81.9289,0.0,0.0,64.2646,0.0,73.0790,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.OFFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.6176,43.0248,58.0061,0.0,21.2119,0.0,0.0,0.0,81.9289,0.0,0.0,64.2646,0.0,73.0790,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
head(countryseriesmetadata)

,Type,Country Code,Series Code,Description
0,Country-Series,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
1,Country-Series,Afghanistan (AFG),"External debt stocks, total (DOD, current US$)...","Long-term public and publicly guaranteed, long..."
2,Country-Series,Angola (AGO),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
3,Country-Series,Angola (AGO),"External debt stocks, total (DOD, current US$)...",Long-term public and publicly guaranteed debt ...
4,Country-Series,Albania (ALB),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...

In [20]:
head(countrymetadata)

,Code,Long Name,Income Group,Region,Lending category,Other groups,Currency Unit,Latest population census,Latest household survey,Special Notes,National accounts base year,National accounts reference year,System of National Accounts,SNA price valuation,PPP survey years,Balance of Payments Manual in use,External debt Reporting status,System of trade,Government Accounting concept,IMF data dissemination standard,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,2-alpha code,WB-2 code,Table Name,Short Name
0,AFG,Islamic State of Afghanistan,Low income,South Asia,IDA,HIPC,Afghan afghani,1979,"Demographic and Health Survey, 2015",The reporting period for national accounts dat...,2016,NaN,Country uses the 1993 System of National Accou...,Value added at basic prices (VAB),PPPs are imputed for 2011 and 2017 based on a ...,BPM6,Estimate,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,"Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0,2000.0,AF,AF,Afghanistan,Afghanistan
1,ALB,Republic of Albania,Upper middle income,Europe & Central Asia,IBRD,NaN,Albanian lek,2020 (expected),"Demographic and Health Survey, 2017/18",NaN,Original chained constant price data are resca...,2010.0,Country uses the 2008 System of National Accou...,Value added at basic prices (VAB),Rolling surveys (annual estimation),BPM6,Actual,Special trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2018.0,2006.0,AL,AL,Albania,Albania
2,DZA,People's Democratic Republic of Algeria,Lower middle income,Middle East & North Africa,IBRD,NaN,Algerian dinar,2020 (expected),"Multiple Indicator Cluster Survey, 2018/19",NaN,Original chained constant price data are resca...,2012.0,Country uses the 1993 System of National Accou...,Value added at basic prices (VAB),"2017, 2011",BPM6,Actual,Special trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,"Integrated household survey (IHS), 2011",NaN,NaN,2010.0,2017.0,2012.0,DZ,DZ,Algeria,Algeria
3,AGO,People's Republic of Angola,Lower middle income,Sub-Saharan Africa,IBRD,NaN,Angolan kwanza,2014,"Demographic and Health Survey, 2015/16",The World Bank systematically assesses the app...,2002,NaN,Country uses the 1993 System of National Accou...,Value added at basic prices (VAB),"2017, 2011",BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,"Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2018.0,2005.0,AO,AO,Angola,Angola
4,ARG,Argentine Republic,Upper middle income,Latin America & Caribbean,IBRD,NaN,Argentine peso,2020 (expected),"Multiple Indicator Cluster Survey, 2019/20",The World Bank systematically assesses the app...,2004,NaN,Country uses the 2008 System of National Accou...,Value added at basic prices (VAB),2017,BPM6,Actual,Special trade system,Consolidated central government,Special Data Dissemination Standard (SDDS),"Integrated household survey (IHS), 2016",Yes,2008,2002.0,2018.0,2011.0,AR,AR,Argentina,Argentina

In [21]:
head(footnotes)

,Type,Country Code,Series Code,Time Code,Description
0,FootNote,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",1970 (YR1970),Source: United Nations Conference on Trade and...
1,FootNote,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",1971 (YR1971),Source: United Nations Conference on Trade and...
2,FootNote,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",1972 (YR1972),Source: United Nations Conference on Trade and...
3,FootNote,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",1973 (YR1973),Source: United Nations Conference on Trade and...
4,FootNote,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",1976 (YR1976),Source: United Nations Conference on Trade and...

In [22]:
head(seriesmetadata)

,Code,License Type,Indicator Name,Short definition,Long definition,Source,Topic,Dataset,Periodicity,Aggregation method,General comments
0,DT.GPA.DPPG,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN
1,DT.GPA.OFFT,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN
2,DT.GPA.PRVT,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN
3,DT.GRE.DPPG,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN
4,DT.GRE.OFFT,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN

# Printing Last 5 Rows

In [23]:
tail(allcountry)

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
76815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76818,Data from database: International Debt Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76819,Last Updated: 12/06/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
tail(countryseriesmetadata)

,Type,Country Code,Series Code,Description
255,Country-Series,South Africa (ZAF),"External debt stocks, total (DOD, current US$)...",Long-term public and publicly guaranteed and l...
256,Country-Series,Zambia (ZMB),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
257,Country-Series,Zambia (ZMB),"External debt stocks, total (DOD, current US$)...",Long-term public and publicly guaranteed and l...
258,Country-Series,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
259,Country-Series,Zimbabwe (ZWE),"External debt stocks, total (DOD, current US$)...",Long-term public and publicly guaranteed and l...

In [25]:
tail(countrymetadata)

,Code,Long Name,Income Group,Region,Lending category,Other groups,Currency Unit,Latest population census,Latest household survey,Special Notes,National accounts base year,National accounts reference year,System of National Accounts,SNA price valuation,PPP survey years,Balance of Payments Manual in use,External debt Reporting status,System of trade,Government Accounting concept,IMF data dissemination standard,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,2-alpha code,WB-2 code,Table Name,Short Name
130,VUT,Republic of Vanuatu,Lower middle income,East Asia & Pacific,IDA,NaN,Vanuatu vatu,2020 (expected),"Multiple Indicator Cluster Survey, 2007/08",NaN,2006,NaN,Country uses the 1993 System of National Accou...,Value added at basic prices (VAB),2011 (Only for individual consumption expendit...,BPM6,Actual,NaN,Budgetary central government,Enhanced General Data Dissemination System (e-...,"Integrated household survey (IHS), 2010",NaN,2007,NaN,2011.0,NaN,VU,VU,Vanuatu,Vanuatu
131,VNM,Socialist Republic of Vietnam,Lower middle income,East Asia & Pacific,IBRD,NaN,Vietnamese dong,2019,"Multiple Indicator Cluster Survey, 2020/21",NaN,2010,NaN,Country uses the 1993 System of National Accou...,Value added at basic prices (VAB),"2017, 2011",BPM6,Actual,General trade system,NaN,Enhanced General Data Dissemination System (e-...,"Integrated household survey (IHS), 2016",Yes,2016,2013.0,2017.0,2005.0,VN,VN,Vietnam,Vietnam
132,YEM,Republic of Yemen,Low income,Middle East & North Africa,IDA,NaN,Yemeni rial,2004,"Demographic and Health Survey, 2013",The World Bank systematically assesses the app...,1990,NaN,Country uses the 1993 System of National Accou...,Value added at basic prices (VAB),Annual estimation for 2011-2013,BPM5 (Converted into BPM6 by IMF),Estimate,Special trade system,NaN,Enhanced General Data Dissemination System (e-...,"Expenditure survey/budget survey (ES/BS), 2014",NaN,NaN,2012.0,2015.0,2005.0,YE,RY,"Yemen, Rep.",Yemen
133,ZMB,Republic of Zambia,Low income,Sub-Saharan Africa,IDA,HIPC,New Zambian kwacha,2020 (expected),"Demographic and Health Survey, 2018",National accounts data were rebased to reflect...,2010,NaN,Country uses the 2008 System of National Accou...,Value added at basic prices (VAB),"2017, 2011",BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,"Integrated household survey (IHS), 2015",NaN,NaN,1994.0,2018.0,2002.0,ZM,ZM,Zambia,Zambia
134,ZWE,Republic of Zimbabwe,Lower middle income,Sub-Saharan Africa,Blend,NaN,Zimbabwean Dollar,2012,"Multiple Indicator Cluster Survey, 2019",National Accounts data are reported in Zimbabw...,2012,NaN,Country uses the 2008 System of National Accou...,Value added at basic prices (VAB),"2017, 2011",BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,"Integrated household survey (IHS), 2011/12",NaN,NaN,NaN,2018.0,2007.0,ZW,ZW,Zimbabwe,Zimbabwe

In [26]:
tail(footnotes)

,Type,Country Code,Series Code,Time Code,Description
2022,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",2006 (YR2006),Source: United Nations Conference on Trade and...
2023,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",2007 (YR2007),Source: United Nations Conference on Trade and...
2024,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",2008 (YR2008),Source: United Nations Conference on Trade and...
2025,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",2021 (YR2021),Gap-filled with countries' balance of payments...
2026,FootNote,Zimbabwe (ZWE),Personal transfers and compensation of employe...,2021 (YR2021),Gap-filled with countries' balance of payments...

In [27]:
tail(seriesmetadata)

,Code,License Type,Indicator Name,Short definition,Long definition,Source,Topic,Dataset,Periodicity,Aggregation method,General comments
564,DT.UND.OFFT.CD,NaN,"Undisbursed external debt, official creditors ...",Undisbursed debt is the total public and publi...,Undisbursed debt is the total public and publi...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Undisbu...,International Debt Statistics,Annual,Sum,NaN
565,DT.UND.PRVT.CD,NaN,"Undisbursed external debt, private creditors (...",Undisbursed debt is the total public and publi...,Undisbursed debt is the total public and publi...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Undisbu...,International Debt Statistics,Annual,Sum,NaN
566,DT.UND.DPPG.CD,NaN,"Undisbursed external debt, total (UND, current...",Undisbursed debt is the total public and publi...,Undisbursed debt is the total public and publi...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Undisbu...,International Debt Statistics,Annual,Sum,NaN
567,DT.DOD.DIMF.CD,NaN,"Use of IMF credit (DOD, current US$)",Use of IMF credit denotes members drawings on...,Use of IMF Credit: Data related to the operati...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Debt ou...,International Debt Statistics,Annual,Sum,NaN
568,DT.DOD.DSDR.CD,NaN,"Use of IMF credit, SDR allocations (DOD, curre...",SDR allocations are also included in this cate...,SDR allocations are also included in this cate...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Debt ou...,International Debt Statistics,Annual,Sum,NaN

# Printing Random 10 Rows

In [28]:
sample(allcountry)

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
7385,Bolivia,BOL,World,WLD,Technical cooperation grants (current US$),BX.GRT.TECH.CD.DT,9370000.0,12070000.0,10490000.0,13040000.0,11060000.0,15260000.0,17830000.0,22410000.0,28690000.0,31450000.0,40510000.0,36130000.0,26810000.0,28270000.0,29090000.0,42440000.0,58140000.0,79040000.0,84100000.0,91040000.0,106400000.0,153040000.0,170290000.0,184350000.0,1.823400e+08,2.100200e+08,1.836700e+08,1.888700e+08,189880000.0,1.856100e+08,1.412600e+08,2.201400e+08,2.014400e+08,2.562300e+08,2.336600e+08,236570000.0,2.990900e+08,1.055800e+08,1.345300e+08,1.539300e+08,1.281300e+08,1.105600e+08,1.173600e+08,9.671000e+07,9.333000e+07,7.940000e+07,7.491000e+07,7.191000e+07,7.108000e+07,5.440000e+07,5.608000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17042,Costa Rica,CRI,World,WLD,"PS, other private creditors (AMT, current US$)",DT.AMT.PROP.PS.CD,668000.0,1065000.0,1376000.0,3759000.0,6168386.1,7480517.9,7283000.0,8652000.0,8010000.0,11643000.0,10028000.0,8798000.0,1918000.0,4208754.0,10962227.8,6638469.9,6117415.6,4029444.4,3783805.9,2835271.4,4953249.6,3796327.4,6523215.2,3577151.4,5.804486e+06,4.617973e+06,3.736073e+06,3.136386e+06,4134445.2,2.538068e+06,3.052816e+06,2.076197e+06,1.549994e+06,1.681732e+06,1.500428e+06,835000.0,6.400000e+04,7.810000e+05,2.486000e+06,1.872000e+06,2.293000e+06,3.203000e+06,3.907000e+06,9.877000e+06,8.450000e+06,3.014700e+07,2.081100e+07,1.420000e+07,9.554000e+06,2.489000e+06,6.280000e+05,8.876700e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62123,South Africa,ZAF,World,WLD,"Debt service on external debt, private nonguar...",DT.TDS.DPNG.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.128000e+09,1.160000e+09,1.457500e+09,3.380803e+09,679646000.0,2.614445e+09,1.178377e+09,1.474296e+09,3.027934e+09,1.741259e+09,1.650428e+09,211641000.0,2.581840e+09,8.078240e+08,2.877679e+09,1.359753e+09,2.410557e+09,2.107375e+09,3.517565e+09,3.973501e+09,4.262808e+09,1.007917e+10,7.747025e+09,8.365189e+09,1.219382e+10,1.268561e+10,1.574261e+10,1.441937e+10,1.869667e+09,1.279246e+09,1.876504e+09,2.391024e+09,2.016992e+09,2.067042e+09,1.604901e+09,454507000.0
43069,Madagascar,MDG,World,WLD,"PPG, official creditors (TDS, current US$)",DT.TDS.OFFT.CD,60638442.4,66364374.1,72748338.4,82730089.6,84534142.0,62816346.3,9919592.0,135171778.9,12088773.6,14698218.9,26616766.2,22882372.8,33482201.0,30522274.3,46145542.4,76608298.3,76175201.3,136835342.2,112106954.1,135531106.4,125373191.7,97801838.6,62104587.5,50124715.7,4.442570e+07,3.413044e+07,5.502418e+07,1.912109e+08,108234839.3,1.393992e+08,1.016693e+08,5.945537e+07,5.849457e+07,6.476421e+07,7.334753e+07,65074948.5,5.406684e+07,1.811554e+07,2.544957e+07,4.197079e+07,5.371949e+07,4.175612e+07,5.940610e+07,5.685109e+07,7.519731e+07,1.104336e+08,8.848485e+07,9.932607e+07,9.448113e+07,8.193972e+07,8.674011e+07,1.013402e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13224,Chad,TCD,World,WLD,"GG, bilateral (DIS, current US$)",DT.DIS.BLAT.GG.CD,1545935.3,1305202.5,1062754.5,3366747.8,12911735.6,60991856.4,345082.1,3084709.2,33924.6,2198800.2,0.0,0.0,0.0,186032.2,3486013.9,1787254.6,2266980.0,1528063.3,8790226.6,9933035.2,21618272.7,22740088.1,8072956.9,1401124.6,5.433513e+06,0.000000e+00,1.708945e+06,9.486272e+06,2256875.9,1.036163e+07,9.843781e+06,7.500028e+06,5.172218e+06,1.427533e+07,2.871532e+06,1952073.3,3.052971e+07,1.153600e+07,5.908567e+07,5.260000e+05,3.017880e+08,1.943031e+08,3.978433e+07,3.036795e+07,7.582700e+07,9.995067e+06,8.068608e+07,1.465713e+08,4.730805e+07,2.797019e+07,7.950841e+07,3.671817e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70742,Turkiye,TUR,World,WLD,"GG, other private creditors (DIS, current US$)",DT.DIS.PROP.GG.CD,20666558.3,9016902.6,16073080.0,15161139.7,10390564.8,707386.2,10983506.5,21083829.1,46634895.8,22038687.9,29415317.4,7493679.3,10455668.0,981555.7,699628.3,10701321.0,59819999.2,85533744.8,118953687.0,103374881.5,76342811.3,218204406.0,119926141.0,75711616.2,4.595761e+08,2.283533e+08,1.299385e+08,5.774310e+08,225765436.4,4.366824e+08,1.484363e+08,1.241449e+08,1.308879e+08,1.234904e+08,1.154095e+08,73758000.0,2.887500e+07,2.021030e+08,2.064030e+08,1.707290e+08,4.083369e+08,9.036725e+07,3.431124e+07,3.809358e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11937,Cambodia,KHM,World,WLD,Technical cooperation grants (current US$),BX.GRT.TECH.CD.DT,7050000.0,7560000.0,8980000.0,6880000.0,8400000.0,3550000.0,720000.0,300000.0,250000.0,38500000.0,144830000.0,76400000.0,13190000.0,8780000.0,8990000.0,6500000.0,7900000.0,7840000.0,8280000.0,11540000.0,18690000.0,49000000.0,101750000.0,118970000.0,1.031200e+08,1.377000e+08,1.444000e+08,1.228700e+08,120960000.0,9.402000e+07,9.979000e+07,1.197900e+08,1.336400e+08,1.624200e+08,1.547300e+08,182010000.0,1.809800e+08,1.304100e+08,1.496300e+08,1.561600e+08,1.855500e+08,1.952200e+08,1.966300e+08,1.520600e+08,1.479000e+08,1.130400e+08,1.256800e+08,1.257800e+08,1.214800e+08,1.139400e+08,9.258000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25114,"Gambia, The",GMB,World,WLD,"Commitments, multilateral creditors (COM, curr...",DT.COM.MLAT.CD,2100000.0,NaN,1300000.0,NaN,4940164.8,350000.0,13708200.0,3985150.0,11098000.0,28302619.6,20203163.4,3419583.5,29865003.1,14561147.1,34462666.0,2930677.5,38443169.8,14408075.0,24092700.2,59095285.7,37920335.5,5854230.4,20586871.8,12300000.0,3.887766e+07,5.295159e+06,4.936069e+06,2.648064e+07,46476879.8,4.912239e+07,1.947049e+07,6.857619e+07,6.392281e+07,2.750000e+06,3.173004e+07,26476391.5,3.870187e+07,3.173538e+07,3.200767e+07,1.977270e+07,3.233451e+07,7.892967e+07,3.097144e+07,4.874861e+07,4.042000e+07,7.939737e+07,3.473569e+07,3.631922e+07,9.402092e+07,3.537198e+07,8.568273e+05,2.060228e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7402,Bosnia and Herzegovina,BIH,World,WLD,Average grant element on new external debt com...,DT.GRE.PRVT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.283000e+01,8.081200e+00,2.693110e+01,2.788320e+01,2.339970e+01,1.888370e+01,2.072530e+01,2.644960e+01,3.116680e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.082400e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36749,Kosovo,XKX,World,WLD,"PNG, commercial banks and other creditors (NFL...",DT.NFL.PNGC.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.065820e+08,1.237690e+08,2.890500e+07,1.081850e+08,8.355100e+07,2.540600e+07,5.054700e+07,-2.429900e+07,1.283600e+07,6.782500e+07,9.377300e+07,1.289800e+07,9.183000e+07,1.505530e+08,2.012180e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
sample(countryseriesmetadata)

,Type,Country Code,Series Code,Description
241,Country-Series,St. Vincent and the Grenadines (VCT),"External debt stocks, total (DOD, current US$)...",Long-term public and publicly guaranteed debt ...
180,Country-Series,Philippines (PHL),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
123,Country-Series,Lao PDR (LAO),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
110,Country-Series,Jamaica (JAM),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
5,Country-Series,Albania (ALB),"External debt stocks, total (DOD, current US$)...",Long-term public and publicly guaranteed and l...
57,Country-Series,Costa Rica (CRI),"External debt stocks, total (DOD, current US$)...","Long-term public and publicly guaranteed debt,..."
239,Country-Series,Uzbekistan (UZB),"External debt stocks, total (DOD, current US$)...",Long-term public and publicly guaranteed and l...
170,Country-Series,Nigeria (NGA),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
192,Country-Series,Sudan (SDN),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
48,Country-Series,"Congo, Rep. (COG)","Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...

In [30]:
sample(countrymetadata)

,Code,Long Name,Income Group,Region,Lending category,Other groups,Currency Unit,Latest population census,Latest household survey,Special Notes,National accounts base year,National accounts reference year,System of National Accounts,SNA price valuation,PPP survey years,Balance of Payments Manual in use,External debt Reporting status,System of trade,Government Accounting concept,IMF data dissemination standard,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,2-alpha code,WB-2 code,Table Name,Short Name
120,TLS,Democratic Republic of Timor-Leste,Lower middle income,East Asia & Pacific,Blend,NaN,U.S. dollar,2015,"Demographic and Health Survey, 2016",NaN,2015,NaN,Country uses the 2008 System of National Accou...,Value added at basic prices (VAB),PPPs are imputed for 2011 and 2017 based on a ...,NaN,Actual,General trade system,NaN,Enhanced General Data Dissemination System (e-...,Living Standards Measurement Study Survey (LSM...,NaN,NaN,NaN,2017.0,2004.0,TL,TP,Timor-Leste,Timor-Leste
35,ECU,Republic of Ecuador,Upper middle income,Latin America & Caribbean,IBRD,NaN,U.S. dollar,2020 (expected),"Reproductive Health Survey, 2004",NaN,2007,NaN,Country uses the 2008 System of National Accou...,Value added at basic prices (VAB),"2017, 2011",BPM6,Actual,Special trade system,NaN,Special Data Dissemination Standard (SDDS),"Integrated household survey (IHS), 2018",NaN,NaN,2008.0,2018.0,2005.0,EC,EC,Ecuador,Ecuador
88,MOZ,Republic of Mozambique,Low income,Sub-Saharan Africa,IDA,HIPC,New Mozambican metical,2017,"Malaria Indicator Survey, 2018",NaN,2014,NaN,Country uses the 2008 System of National Accou...,Value added at basic prices (VAB),"2017, 2011",BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,"Expenditure survey/budget survey (ES/BS), 2014",NaN,2009-2010,1973.0,2018.0,2001.0,MZ,MZ,Mozambique,Mozambique
119,THA,Kingdom of Thailand,Upper middle income,East Asia & Pacific,IBRD,NaN,Thai baht,2020 (expected),"Multiple Indicator Cluster Survey, 2019",Fiscal year end: September 30; reporting perio...,Original chained constant price data are resca...,2002.0,Country uses the 2008 System of National Accou...,Value added at producer prices (VAP),"2017, 2011",BPM6,Actual,Special trade system,Consolidated central government,Special Data Dissemination Standard (SDDS),"Integrated household survey (IHS), 2015",NaN,2013,2011.0,2018.0,2007.0,TH,TH,Thailand,Thailand
98,PER,Republic of Peru,Upper middle income,Latin America & Caribbean,IBRD,NaN,Peruvian new sol,2017,"Continuous Demographic and Health Survey, 2014",The World Bank systematically assesses the app...,2007,NaN,Country uses the 2008 System of National Accou...,Value added at basic prices (VAB),"2017, 2011",BPM6,Actual,Special trade system,Consolidated central government,Special Data Dissemination Standard (SDDS),"Integrated household survey (IHS), 2017",NaN,2012,2011.0,2018.0,2008.0,PE,PE,Peru,Peru
33,DOM,Dominican Republic,Upper middle income,Latin America & Caribbean,IBRD,NaN,Dominican peso,2020 (expected),"Multiple Indicator Cluster Survey, 2019",NaN,Original chained constant price data are resca...,2007.0,Country uses the 2008 System of National Accou...,Value added at basic prices (VAB),"2017, 2011",BPM6,Actual,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,"Integrated household survey (IHS), 2016",NaN,2015,1984.0,2017.0,2010.0,DO,DO,Dominican Republic,Dominican Republic
77,MDV,Republic of Maldives,Upper middle income,South Asia,IDA,NaN,Maldivian rufiyaa,2014,"Demographic and Health Survey, 2016/17",NaN,2014,NaN,Country uses the 1993 System of National Accou...,Value added at basic prices (VAB),"2017, 2011",BPM6,Actual,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,"Integrated household survey (IHS), 2009/10",Yes,NaN,NaN,2018.0,2008.0,MV,MV,Maldives,Maldives
83,MIC,Middle income,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Middle income group aggregate. Middle-income e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,XP,XP,Middle income,Middle income
46,GHA,Republic of Ghana,Lower middle income,Sub-Saharan Africa,IDA,HIPC,New Ghanaian cedi,2020 (expected),"Malaria Indicator Survey, 2019",The World Bank systematically assesses the app...,2013,NaN,Country uses the 2008 System of National Accou...,Value added at basic prices (VAB),"2017, 2011",BPM6,Actual,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,Living Standards Measurement Study Survey (LSM...,NaN,NaN,2003.0,2018.0,2000.0,GH,GH,Ghana,Ghana
20,KHM,Kingdom of Cambodia,Lower middle income,East Asia & Pacific,IDA,NaN,Cambodian riel,2019,"Demographic and Health Survey, 2020",The World Bank systematically assesses the app...,2000,NaN,Country uses the 1993 System of National Accou...,Value added at basic prices (VAB),"2017, 2011",BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,"Integrated household survey (IHS), 2012",NaN,2013,2000.0,2016.0,2006.0,KH,KH,Cambodia,Cambodia

In [31]:
sample(footnotes)

,Type,Country Code,Series Code,Time Code,Description
1084,FootNote,Mauritius (MUS),"Foreign direct investment, net inflows in repo...",2012 (YR2012),Source: United Nations Conference on Trade and...
1828,FootNote,Uzbekistan (UZB),"Foreign direct investment, net inflows in repo...",2004 (YR2004),Source: United Nations Conference on Trade and...
2001,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1997 (YR1997),Source: United Nations Conference on Trade and...
1363,FootNote,Samoa (WSM),"Foreign direct investment, net inflows in repo...",1973 (YR1973),Source: United Nations Conference on Trade and...
1516,FootNote,Somalia (SOM),"Exports of goods, services and primary income ...",2018 (YR2018),Gap-filled with countries' balance of payments...
966,FootNote,Madagascar (MDG),"Foreign direct investment, net inflows in repo...",2021 (YR2021),Source: United Nations Conference on Trade and...
375,FootNote,"Congo, Dem. Rep. (COD)","Foreign direct investment, net inflows in repo...",1973 (YR1973),Source: United Nations Conference on Trade and...
1600,FootNote,Sudan (SDN),"Foreign direct investment, net inflows in repo...",1994 (YR1994),Source: United Nations Conference on Trade and...
1983,FootNote,Zambia (ZMB),"Foreign direct investment, net inflows in repo...",1992 (YR1992),Source: United Nations Conference on Trade and...
899,FootNote,Lebanon (LBN),"Portfolio investment, equity (DRS, current US$...",2021 (YR2021),Gap-filled with countries' balance of payments...

In [32]:
sample(seriesmetadata)

,Code,License Type,Indicator Name,Short definition,Long definition,Source,Topic,Dataset,Periodicity,Aggregation method,General comments
307,DT.AMT.PROP.OPS.CD,NaN,"OPS, other private creditors (AMT, current US$)",Other public sector other private credits from...,Other public sector other private credits from...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Amortiz...,International Debt Statistics,Annual,Sum,NaN
555,DT.DOD.RSDL.CD,NaN,"Residual, debt stock-flow reconciliation (curr...","The residual difference, i.e. the change in st...","The residual difference, i.e. the change in st...","World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Arrears...,International Debt Statistics,Annual,Sum,NaN
142,DT.TDS.BLAT.GG.CD,NaN,"GG, bilateral (TDS, current US$)",General government debt includes loans from go...,General government debt includes loans from go...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Debt se...,International Debt Statistics,Annual,Sum,NaN
269,DT.NFL.BLTC.OPS.CD,NaN,"OPS, bilateral concessional (NFL, current US$)",Other public sector bilateral debt includes lo...,Other public sector bilateral debt includes lo...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Net flows,International Debt Statistics,Annual,Sum,NaN
291,DT.NTR.MLAT.OPS.CD,NaN,"OPS, multilateral (NTR, current US$)",Other public sector multilateral loans include...,Other public sector multilateral loans include...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Net tra...,International Debt Statistics,Annual,Sum,NaN
469,DT.NTR.MLTC.PRVG.CD,NaN,"PRVG, multilateral concessional (NTR, current ...",Private sector guaranteed by Public Sector mul...,Private sector guaranteed by Public Sector mul...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Net tra...,International Debt Statistics,Annual,Sum,NaN
99,DT.TDS.DLXF.CD,NaN,"Debt service on external debt, long-term (TDS,...",Debt service payments are the sum of principal...,Debt service payments are the sum of principal...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Debt se...,International Debt Statistics,Annual,Sum,NaN
208,DT.IXA.DLXF.CD,NaN,"Interest arrears, long-term DOD (current US$)",Interest in arrears on long-term debt is defin...,Interest in arrears on long-term debt is defin...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Arrears...,International Debt Statistics,Annual,Sum,NaN
564,DT.UND.OFFT.CD,NaN,"Undisbursed external debt, official creditors ...",Undisbursed debt is the total public and publi...,Undisbursed debt is the total public and publi...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Undisbu...,International Debt Statistics,Annual,Sum,NaN
388,DT.AMT.OFFT.CD,NaN,"PPG, official creditors (AMT, current US$)",Public and publicly guaranteed debt from offic...,Public and publicly guaranteed debt from offic...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Amortiz...,International Debt Statistics,Annual,Sum,NaN

# Printing Total Number of Rows and Columns

In [33]:
shape(allcountry)

(76820, 66)

In [34]:
shape(countryseriesmetadata)

(260, 4)

In [35]:
shape(countrymetadata)

(135, 30)

In [36]:
shape(footnotes)

(2027, 5)

In [37]:
shape(seriesmetadata)

(569, 11)

# Priniting Dataset Information

In [38]:
info(allcountry)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76820 entries, 0 to 76819
Data columns (total 66 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country Name           76817 non-null  object
 1   Country Code           76815 non-null  object
 2   Counterpart-Area Name  76815 non-null  object
 3   Counterpart-Area Code  76815 non-null  object
 4   Series Name            76815 non-null  object
 5   Series Code            76815 non-null  object
 6   1970                   34740 non-null  float64
 7   1971                   35586 non-null  float64
 8   1972                   36240 non-null  float64
 9   1973                   37015 non-null  float64
 10  1974                   37552 non-null  float64
 11  1975                   38326 non-null  float64
 12  1976                   38764 non-null  float64
 13  1977                   39645 non-null  float64
 14  1978                   40283 non-null  float64
 15  1979                   40542 non-null  float64
 16  1980                   41287 non-null  float64
 17  1981                   42922 non-null  float64
 18  1982                   43241 non-null  float64
 19  1983                   43547 non-null  float64
 20  1984                   44037 non-null  float64
 21  1985                   44417 non-null  float64
 22  1986                   44567 non-null  float64
 23  1987                   44166 non-null  float64
 24  1988                   44024 non-null  float64
 25  1989                   45261 non-null  float64
 26  1990                   45249 non-null  float64
 27  1991                   45063 non-null  float64
 28  1992                   46195 non-null  float64
 29  1993                   47063 non-null  float64
 30  1994                   47717 non-null  float64
 31  1995                   48006 non-null  float64
 32  1996                   48654 non-null  float64
 33  1997                   48639 non-null  float64
 34  1998                   48925 non-null  float64
 35  1999                   50410 non-null  float64
 36  2000                   50027 non-null  float64
 37  2001                   50026 non-null  float64
 38  2002                   49825 non-null  float64
 39  2003                   49596 non-null  float64
 40  2004                   49770 non-null  float64
 41  2005                   49655 non-null  float64
 42  2006                   49779 non-null  float64
 43  2007                   50007 non-null  float64
 44  2008                   49806 non-null  float64
 45  2009                   50035 non-null  float64
 46  2010                   50004 non-null  float64
 47  2011                   49282 non-null  float64
 48  2012                   49197 non-null  float64
 49  2013                   49590 non-null  float64
 50  2014                   50707 non-null  float64
 51  2015                   50226 non-null  float64
 52  2016                   49933 non-null  float64
 53  2017                   50095 non-null  float64
 54  2018                   50005 non-null  float64
 55  2019                   49893 non-null  float64
 56  2020                   50207 non-null  float64
 57  2021                   50104 non-null  float64
 58  2022                   12860 non-null  float64
 59  2023                   12763 non-null  float64
 60  2024                   12657 non-null  float64
 61  2025                   12449 non-null  float64
 62  2026                   12207 non-null  float64
 63  2027                   12042 non-null  float64
 64  2028                   11753 non-null  float64
 65  2029                   11461 non-null  float64
dtypes: float64(60), object(6)
memory usage: 38.7+ MB

In [39]:
info(countryseriesmetadata)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Type          260 non-null    object
 1   Country Code  260 non-null    object
 2   Series Code   260 non-null    object
 3   Description   260 non-null    object
dtypes: object(4)
memory usage: 8.2+ KB

In [40]:
info(countrymetadata)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 30 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Code                                               135 non-null    object
 1   Long Name                                          135 non-null    object
 2   Income Group                                       121 non-null    object
 3   Region                                             121 non-null    object
 4   Lending category                                   121 non-null    object
 5   Other groups                                       40 non-null     object
 6   Currency Unit                                      121 non-null    object
 7   Latest population census                           119 non-null    object
 8   Latest household survey                            118 non-null    object
 9   Special Notes                                      57 non-null     object
 10  National accounts base year                        121 non-null    object
 11  National accounts reference year                   28 non-null     float64
 12  System of National Accounts                        121 non-null    object
 13  SNA price valuation                                121 non-null    object
 14  PPP survey years                                   120 non-null    object
 15  Balance of Payments Manual in use                  120 non-null    object
 16  External debt Reporting status                     121 non-null    object
 17  System of trade                                    102 non-null    object
 18  Government Accounting concept                      98 non-null     object
 19  IMF data dissemination standard                    118 non-null    object
 20  Source of most recent Income and expenditure data  117 non-null    object
 21  Vital registration complete                        38 non-null     object
 22  Latest agricultural census                         72 non-null     object
 23  Latest industrial data                             88 non-null     float64
 24  Latest trade data                                  115 non-null    float64
 25  Latest water withdrawal data                       115 non-null    float64
 26  2-alpha code                                       135 non-null    object
 27  WB-2 code                                          135 non-null    object
 28  Table Name                                         135 non-null    object
 29  Short Name                                         135 non-null    object
dtypes: float64(4), object(26)
memory usage: 31.8+ KB

In [41]:
info(footnotes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2027 entries, 0 to 2026
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Type          2027 non-null   object
 1   Country Code  2027 non-null   object
 2   Series Code   2027 non-null   object
 3   Time Code     2027 non-null   object
 4   Description   2027 non-null   object
dtypes: object(5)
memory usage: 79.3+ KB

In [42]:
info(seriesmetadata)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Code                569 non-null    object
 1   License Type        1 non-null      object
 2   Indicator Name      569 non-null    object
 3   Short definition    568 non-null    object
 4   Long definition     569 non-null    object
 5   Source              569 non-null    object
 6   Topic               569 non-null    object
 7   Dataset             569 non-null    object
 8   Periodicity         569 non-null    object
 9   Aggregation method  569 non-null    object
 10  General comments    7 non-null      object
dtypes: object(11)
memory usage: 49.0+ KB

# Priniting Dataset Columns Name

In [43]:
columns(allcountry)

Index(['Country Name', 'Country Code', 'Counterpart-Area Name',
       'Counterpart-Area Code', 'Series Name', 'Series Code', '1970', '1971',
       '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980',
       '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989',
       '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998',
       '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025',
       '2026', '2027', '2028', '2029'],
      dtype='object')

In [44]:
columns(countryseriesmetadata)

Index(['Type', 'Country Code', 'Series Code', 'Description'], dtype='object')

In [45]:
columns(countrymetadata)

Index(['Code', 'Long Name', 'Income Group', 'Region', 'Lending category',
       'Other groups', 'Currency Unit', 'Latest population census',
       'Latest household survey', 'Special Notes',
       'National accounts base year', 'National accounts reference year',
       'System of National Accounts', 'SNA price valuation',
       'PPP survey years', 'Balance of Payments Manual in use',
       'External debt Reporting status', 'System of trade',
       'Government Accounting concept', 'IMF data dissemination standard',
       'Source of most recent Income and expenditure data',
       'Vital registration complete', 'Latest agricultural census',
       'Latest industrial data', 'Latest trade data',
       'Latest water withdrawal data', '2-alpha code', 'WB-2 code',
       'Table Name', 'Short Name'],
      dtype='object')

In [46]:
columns(footnotes)

Index(['Type', 'Country Code', 'Series Code', 'Time Code', 'Description'], dtype='object')

In [47]:
columns(seriesmetadata)

Index(['Code', 'License Type', 'Indicator Name', 'Short definition',
       'Long definition', 'Source', 'Topic', 'Dataset', 'Periodicity',
       'Aggregation method', 'General comments'],
      dtype='object')


# Priniting Dataset Statistical Information

In [48]:
describe(allcountry)

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
count,3.474000e+04,3.558600e+04,3.624000e+04,3.701500e+04,3.755200e+04,3.832600e+04,3.876400e+04,3.964500e+04,4.028300e+04,4.054200e+04,4.128700e+04,4.292200e+04,4.324100e+04,4.354700e+04,4.403700e+04,4.441700e+04,4.456700e+04,4.416600e+04,4.402400e+04,4.526100e+04,4.524900e+04,4.506300e+04,4.619500e+04,4.706300e+04,4.771700e+04,4.800600e+04,4.865400e+04,4.863900e+04,4.892500e+04,5.041000e+04,5.002700e+04,5.002600e+04,4.982500e+04,4.959600e+04,4.977000e+04,4.965500e+04,4.977900e+04,5.000700e+04,4.980600e+04,5.003500e+04,5.000400e+04,4.928200e+04,4.919700e+04,4.959000e+04,5.070700e+04,5.022600e+04,4.993300e+04,5.009500e+04,5.000500e+04,4.989300e+04,5.020700e+04,5.010400e+04,1.286000e+04,1.276300e+04,1.265700e+04,1.244900e+04,1.220700e+04,1.204200e+04,1.175300e+04,1.146100e+04
mean,2.531202e+08,2.746304e+08,3.093335e+08,3.899016e+08,4.954382e+08,5.914559e+08,6.586655e+08,7.983510e+08,9.458694e+08,1.119965e+09,1.289358e+09,1.400152e+09,1.550912e+09,1.559962e+09,1.622901e+09,1.736494e+09,1.905249e+09,2.202250e+09,2.358747e+09,2.391332e+09,2.625825e+09,2.692258e+09,2.775283e+09,2.964468e+09,3.148774e+09,3.481095e+09,3.583431e+09,3.709205e+09,3.866967e+09,3.708939e+09,3.756043e+09,3.717309e+09,3.790626e+09,4.308671e+09,4.798394e+09,5.106630e+09,5.715478e+09,6.924353e+09,7.524966e+09,7.462679e+09,9.057988e+09,1.042155e+10,1.137218e+10,1.227801e+10,1.246902e+10,1.158232e+10,1.242833e+10,1.406202e+10,1.467573e+10,1.516654e+10,1.538671e+10,1.708152e+10,5.706936e+09,5.317139e+09,5.051286e+09,4.300056e+09,3.916236e+09,3.293999e+09,3.394688e+09,2.727162e+09
std,5.499582e+09,5.899617e+09,6.584283e+09,8.258557e+09,1.034214e+10,1.138485e+10,1.221009e+10,1.371206e+10,1.489215e+10,1.758696e+10,2.039535e+10,2.259922e+10,2.286774e+10,2.266084e+10,2.328343e+10,2.461614e+10,2.601583e+10,2.826091e+10,3.042311e+10,3.157447e+10,3.519055e+10,3.515130e+10,3.612354e+10,3.891640e+10,4.272611e+10,4.725954e+10,5.018669e+10,5.245117e+10,5.300202e+10,5.167533e+10,5.464944e+10,5.495297e+10,5.661484e+10,6.388047e+10,7.457952e+10,8.583775e+10,1.013018e+11,1.250668e+11,1.488523e+11,1.450644e+11,1.757818e+11,2.102564e+11,2.255610e+11,2.405992e+11,2.475542e+11,2.360290e+11,2.386494e+11,2.627312e+11,2.801486e+11,2.878840e+11,2.814026e+11,3.283773e+11,3.730658e+10,3.295846e+10,3.019011e+10,2.477628e+10,2.203872e+10,1.779367e+10,1.809650e+10,1.419355e+10
min,-1.684299e+09,-2.072143e+09,-4.253625e+08,-3.986146e+08,-2.758914e+09,-1.379998e+10,-1.058634e+10,-1.454914e+10,-2.582628e+10,-1.798256e+10,-4.628481e+10,-8.324772e+10,-6.220819e+10,-3.692066e+10,-2.158668e+10,-3.056803e+10,-4.611170e+10,-2.219802e+10,-3.130179e+10,-3.522201e+10,-3.103556e+10,-3.512314e+10,-5.090342e+10,-8.753675e+10,-5.924466e+10,-7.758418e+10,-7.023315e+10,-6.460974e+10,-7.863075e+10,-7.972537e+10,-9.284545e+10,-6.245568e+10,-7.560345e+10,-6.197557e+10,-3.786370e+10,-7.365908e+10,-8.606721e+10,-3.694600e+10,-6.835681e+10,-7.073692e+10,-1.086190e+11,-1.219640e+11,-1.357720e+11,-1.860060e+11,-1.776460e+11,-5.953680e+11,-1.140640e+11,-1.319840e+11,-1.754140e+11,-1.415050e+11,-1.259860e+11,-1.322840e+11,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.572278e-01,2.789121e+00,6.043650e+00,8.210551e+00,1.708602e+01,2.435965e+01,4.327690e+01,6.376000e+02,4.000000e+03,9.137300e+03,2.600000e+04,4.811900e+03,1.600000e+04,3.955000e+02,3.925200e+01,2.225390e+01,2.265235e+01,1.297346e+01,1.426396e+01,1.254920e+01,8.708400e+00,6.579550e+00,8.372369e+00,8.900532e+00,5.737417e+00,5.527950e+00,4.219600e+00,5.527900e+00,2.293400e+00,0.000000e+00,1.029445e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.544697e-01,1.329993e+00,1.803250e+00,3.779652e+00,6.624150e+00,6.515205e+00,8.261800e+00,6.941700e+00,2.634623e+00,3.755908e+00,3.408476e+00,4.822950e+00,3.402100e+00,2.573999e+00,1.833050e+00,5.717582e-01,1.425878e+07,1.511105e+07,1.448100e+07,1.415412e+07,1.354688e+07,1.134293e+07,9.655135e+06,8.612190e+06
50%,1.696030e+06,1.845000e+06,2.334000e+06,2.900000e+06,3.545454e+06,4.547276e+06,5.120417e+06,6.647958e+06,7.512976e+06,9.385000e+06,1.116596e+07,1.041069e+07,1.008443e+07,9.763390e+06,8.594264e+06,8.338961e+06,9.025000e+06,9.399796e+06,1.009385e+07,9.765000e+06,1.012351e+07,1.073700e+07,1.058165e+07,1.072500e+07,1.082187e+07,1.203743e+07,1.129606e+07,1.170660e+07,9.961000e+06,8.147781e+06,8.942172e+06,8.058806e+06,7.629148e+06,8.714448e+06,9.653477e+06,9.922000e+06,1.051307e+07,1.173518e+07,1.263563e+07,1.530954e+07,1.883063e+07,2.107177e+07,2.400800e+07,2.514857e+07,2.500000e+07,2.430708e+07,2.581300e+07,2.933700e+07,3.107839e+07,3.118630e+07,3.485578e+07,3.292133e+07,1.346029e+08,1.440043e+08,1.350701e+08,1.314455e+08,1.221054e+08,1.061135e+08,9.303969e+07,7.918570e+07
75%,2.265691e+07,2.509625e+07,3.120301e+07,3.747082e+07,4.831254e+07,5.927083e+07,6.368009e+07,7.777565e+07,9.190076e+07,1.096688e+08,1.327527e+08,1.374064e+08,1.448550e+08,1.400199e+08,1.323508e+08,1.319147e+08,1.525258e+08,1.596801e+08,1.769030e+08,1.730844e+08,1.814960e+08,1.857823e+08,1.856273e+08,1.881712e+08,1.871634e+08,2.011349e+08,2.001268e+08,2.165787e+08,1.939472e+08,1.774876e+08,1.742550e+08,1.695767e+08,1.719186e+08,1.920389e+08,2.195376e+08,2.235156e+08,2.255817e+08,2.816341e+08,2.984770e+08,3.572936e+08,4.185490e+08,4.493169e+08,5.383443e+08,5.822832e+08,5.685069e+08,5.450789e+08,5.580570e+08,6.595569e+08,6.741350e+08,6.838968e+08,7.357891e+08,7.738234e+08,1.049393e+09,1.014832e+09,1.000000e+09,8.512966e+08,8.253846e+08,7.500000e+08,7.152544e+08,5.884864e+08
max,6.094440e+11,6.577510e+11,7.384270e+11,9.348820e+11,1.184200e+12,1.308550e+12,1.403740e+12,1.575350e+12,1.693140e+12,2.002630e+12,2.335040e+12,2.633570e+12,2.579300e+12,2.492470e+12,2.527010e+12,2.625580e+12,2.709200e+12,2.772940e+12,2.985160e+12,3.126400e+12,3.575050e+12,3.448170e+12,3.567170e+12,3.808970e+12,4.189770e+12,4.719500e+12,5.167340e+12,5.476310e+12,5.312750e+12,5.176860e+12,5.646350e+12,5.709640e+12,5.865420e+12,6.602460e+12,7.847480e+12,9.313210e+12,1.111010e+13,1.377560e+13,1.649940e+13,1.617710e+13,1.962950e+13,2.319250e+13,2.472380e+13,2.615030e+13,2.719070e+13,2.581780e+13,2.604560e+13,2.867070e+13,3.026340e+13,3.103310e+13,2.994460e+13,3.514150e+13,1.196040e+12,1.056970e+12,9.559580e+11,7.575740e+11,6.629790e+11,5.232450e+11,4.984380e+11,3.876790e+11

In [49]:
describe(countryseriesmetadata)

,Type,Country Code,Series Code,Description
count,260,260,260,260
unique,1,132,6,104
top,Country-Series,India (IND),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
freq,260,5,130,130

In [50]:
describe(countrymetadata)

,National accounts reference year,Latest industrial data,Latest trade data,Latest water withdrawal data
count,28.000000,88.000000,115.000000,115.000000
mean,2010.214286,2005.090909,2016.400000,2006.113043
std,4.565224,10.071738,3.679722,4.360439
min,2000.000000,1973.000000,1995.000000,1993.000000
25%,2006.750000,1999.000000,2017.000000,2003.000000
50%,2010.000000,2010.000000,2018.000000,2005.000000
75%,2014.250000,2012.250000,2018.000000,2010.000000
max,2017.000000,2014.000000,2018.000000,2016.000000

In [51]:
describe(footnotes)

,Type,Country Code,Series Code,Time Code,Description
count,2027,2027,2027,2027,2027
unique,1,104,24,52,46
top,FootNote,"Iran, Islamic Rep. (IRN)","Foreign direct investment, net inflows in repo...",2021 (YR2021),Source: United Nations Conference on Trade and...
freq,2027,129,1162,160,1129

In [52]:
describe(seriesmetadata)

,Code,License Type,Indicator Name,Short definition,Long definition,Source,Topic,Dataset,Periodicity,Aggregation method,General comments
count,569,1,569,568,569,569,569,569,569,569,7
unique,569,1,569,555,556,8,20,1,1,3,3
top,DT.GPA.DPPG,CC BY-4.0,Average grace period on new external debt comm...,Private sector guaranteed by Public Sector oth...,Private sector guaranteed by Public Sector oth...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Debt ou...,International Debt Statistics,Annual,Sum,The denominator for this indicator in previous...
freq,1,1,1,2,2,558,75,569,569,534,3

# Feature Engineering

In [53]:
head(allcountry)

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
0,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.DPPG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.2500,8.0833,9.9575,0.0,7.8333,0.0,0.0,0.0,29.8333,0.0,0.0,19.8356,0.0,17.9041,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.OFFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.2500,8.0833,9.9575,0.0,7.8333,0.0,0.0,0.0,29.8333,0.0,0.0,19.8356,0.0,17.9041,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.PRVT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.DPPG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.6176,43.0248,58.0061,0.0,21.2119,0.0,0.0,0.0,81.9289,0.0,0.0,64.2646,0.0,73.0790,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.OFFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.6176,43.0248,58.0061,0.0,21.2119,0.0,0.0,0.0,81.9289,0.0,0.0,64.2646,0.0,73.0790,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
allcountry.head(3)

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
0,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.DPPG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.25,8.0833,9.9575,0.0,7.8333,0.0,0.0,0.0,29.8333,0.0,0.0,19.8356,0.0,17.9041,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.OFFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.25,8.0833,9.9575,0.0,7.8333,0.0,0.0,0.0,29.8333,0.0,0.0,19.8356,0.0,17.9041,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.PRVT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0000,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
data = allcountry[['Country Name','Country Code','Series Name','Series Code']]

In [56]:
data.head()

,Country Name,Country Code,Series Name,Series Code
0,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.DPPG
1,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.OFFT
2,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.PRVT
3,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.DPPG
4,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.OFFT

In [57]:
num = allcountry.select_dtypes(include=['float64'])

In [58]:
num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76820 entries, 0 to 76819
Data columns (total 60 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1970    34740 non-null  float64
 1   1971    35586 non-null  float64
 2   1972    36240 non-null  float64
 3   1973    37015 non-null  float64
 4   1974    37552 non-null  float64
 5   1975    38326 non-null  float64
 6   1976    38764 non-null  float64
 7   1977    39645 non-null  float64
 8   1978    40283 non-null  float64
 9   1979    40542 non-null  float64
 10  1980    41287 non-null  float64
 11  1981    42922 non-null  float64
 12  1982    43241 non-null  float64
 13  1983    43547 non-null  float64
 14  1984    44037 non-null  float64
 15  1985    44417 non-null  float64
 16  1986    44567 non-null  float64
 17  1987    44166 non-null  float64
 18  1988    44024 non-null  float64
 19  1989    45261 non-null  float64
 20  1990    45249 non-null  float64
 21  1991    45063 non-null  float64
 22  1992    46195 non-null  float64
 23  1993    47063 non-null  float64
 24  1994    47717 non-null  float64
 25  1995    48006 non-null  float64
 26  1996    48654 non-null  float64
 27  1997    48639 non-null  float64
 28  1998    48925 non-null  float64
 29  1999    50410 non-null  float64
 30  2000    50027 non-null  float64
 31  2001    50026 non-null  float64
 32  2002    49825 non-null  float64
 33  2003    49596 non-null  float64
 34  2004    49770 non-null  float64
 35  2005    49655 non-null  float64
 36  2006    49779 non-null  float64
 37  2007    50007 non-null  float64
 38  2008    49806 non-null  float64
 39  2009    50035 non-null  float64
 40  2010    50004 non-null  float64
 41  2011    49282 non-null  float64
 42  2012    49197 non-null  float64
 43  2013    49590 non-null  float64
 44  2014    50707 non-null  float64
 45  2015    50226 non-null  float64
 46  2016    49933 non-null  float64
 47  2017    50095 non-null  float64
 48  2018    50005 non-null  float64
 49  2019    49893 non-null  float64
 50  2020    50207 non-null  float64
 51  2021    50104 non-null  float64
 52  2022    12860 non-null  float64
 53  2023    12763 non-null  float64
 54  2024    12657 non-null  float64
 55  2025    12449 non-null  float64
 56  2026    12207 non-null  float64
 57  2027    12042 non-null  float64
 58  2028    11753 non-null  float64
 59  2029    11461 non-null  float64
dtypes: float64(60)
memory usage: 35.2 MB

In [59]:
num.head()

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.2500,8.0833,9.9575,0.0,7.8333,0.0,0.0,0.0,29.8333,0.0,0.0,19.8356,0.0,17.9041,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.2500,8.0833,9.9575,0.0,7.8333,0.0,0.0,0.0,29.8333,0.0,0.0,19.8356,0.0,17.9041,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.6176,43.0248,58.0061,0.0,21.2119,0.0,0.0,0.0,81.9289,0.0,0.0,64.2646,0.0,73.0790,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.6176,43.0248,58.0061,0.0,21.2119,0.0,0.0,0.0,81.9289,0.0,0.0,64.2646,0.0,73.0790,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
num.tail()

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
76815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76819,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
num.sample(10)

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
8370,3.201800e+06,2.924506e+06,2.793674e+06,3.131875e+06,2.942152e+06,5.175000e+04,2.188450e+06,2.174650e+06,2.874650e+06,4.686975e+06,7.824938e+06,9.696355e+06,4.072261e+07,3.757103e+07,4.018152e+07,3.239111e+07,3.924577e+07,5.116882e+07,4.786182e+07,4.239372e+07,2.740563e+07,2.463664e+07,2.077092e+07,4.790311e+07,4.999815e+07,4.695297e+07,3.586250e+07,27609233.4,2.421480e+07,3.194312e+07,2.787757e+07,1.934400e+07,1.709700e+07,1.483600e+07,1.400200e+07,1.171100e+07,9.398000e+06,7.101000e+06,2.000000e+06,1.500000e+06,1.000000e+06,7.500000e+05,0.000000e+00,NaN,3.996000e+07,3.108000e+07,2.220000e+07,1.332000e+07,4.440000e+06,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60314,5.559500e+00,9.396100e+00,6.466500e+00,3.729700e+00,1.899700e+00,5.643800e+00,1.310600e+00,4.782600e+00,1.585000e+00,5.175400e+00,5.454200e+00,6.035200e+00,6.602800e+00,1.022050e+01,8.778300e+00,8.182100e+00,9.647300e+00,1.021590e+01,9.843500e+00,9.137000e+00,8.857100e+00,1.034400e+01,9.406500e+00,1.021890e+01,8.980000e+00,7.823700e+00,8.510800e+00,0.0,5.699600e+00,2.500000e-01,1.025640e+01,1.149530e+01,7.629200e+00,9.677100e+00,7.985500e+00,8.540300e+00,8.419600e+00,5.463200e+00,9.198900e+00,8.882700e+00,8.616900e+00,5.048300e+00,6.823300e+00,7.528800e+00,9.378300e+00,6.264400e+00,6.286400e+00,5.823300e+00,6.358800e+00,7.293800e+00,5.671100e+00,8.797700e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65939,6.150000e+06,8.237000e+06,1.027000e+07,1.112100e+07,2.972900e+07,4.201000e+07,9.297000e+06,2.542000e+06,1.230500e+07,8.811900e+07,2.698800e+07,1.328700e+07,2.007300e+07,7.685200e+07,3.456700e+07,-1.110000e+05,-5.880000e+05,4.759000e+06,3.720000e+07,2.578000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,1.155110e+08,8.553000e+06,1.469000e+06,-1.123700e+07,-6.230000e+06,-7.387000e+06,-2.716100e+07,-1.028900e+07,-1.088000e+07,-8.944000e+06,6.440000e+07,9.618700e+07,-1.000800e+07,-6.975000e+06,-2.365000e+06,-1.124200e+07,-1.647400e+07,0.000000e+00,0.000000e+00,5.302770e+08,-8.404000e+06,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56065,6.846486e+06,8.644526e+06,9.712592e+06,3.070276e+07,1.937286e+07,2.232276e+07,2.560454e+07,3.418643e+07,3.966158e+07,7.155964e+07,7.111926e+07,7.786294e+07,7.212513e+07,6.026422e+07,4.468716e+07,5.621954e+07,5.776483e+07,4.834598e+07,2.743780e+07,5.819109e+07,1.816248e+07,1.326597e+08,8.546037e+07,2.319787e+08,4.343414e+07,3.418080e+07,2.884140e+07,28732164.6,1.282314e+07,9.140552e+06,6.852723e+06,5.838884e+06,4.672423e+06,3.222235e+06,2.053909e+06,1.536367e+06,1.072411e+06,5.774626e+05,4.473412e+05,3.026382e+05,1.969213e+05,1.471252e+05,1.514832e+05,9.725630e+04,1.325544e+05,3.370821e+05,3.451737e+05,3.575189e+05,3.680000e+05,4.120000e+05,3.770000e+05,2.920000e+05,2.920000e+05,2.920000e+05,0.000000e+00,NaN,NaN,NaN,NaN,NaN
54977,NaN,NaN,NaN,NaN,3.931486e+06,4.158831e+06,6.505688e+06,6.765456e+06,7.857217e+06,7.732706e+06,7.179339e+06,5.688454e+06,4.888658e+06,4.490016e+06,1.744617e+07,6.922224e+06,7.194072e+06,8.547281e+06,8.882485e+06,3.519013e+06,2.608907e+06,2.797064e+06,2.671214e+06,2.706403e+06,3.086653e+06,2.438755e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.187500e+07,4.187500e+07,4.187500e+07,4.187400e+07,4.187400e+07,4.187400e+07,4.187400e+07,4.187400e+07,4.187400e+07,4.187400e+07,NaN
12406,1.393943e+05,2.122709e+05,1.470360e+05,3.372572e+05,5.797969e+05,6.463023e+05,4.889880e+05,6.192403e+05,8.551961e+05,5.168387e+05,9.166558e+05,8.351740e+04,2.257469e+05,8.058162e+05,8.781277e+05,8.420631e+05,1.041053e+06,1.434476e+06,1.735572e+06,9.061810e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1180259.8,3.753715e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.400000e+06,3.326600e+07,-1.930000e+06,-2.430000e+06,-1.292000e+06,-4.514000e+06,-4296566.4,1.482798e+07,2.361170e+06,1.778048e+06,2.186617e+06,-3.378586e+06,-1.503505e+06,-1.609210e+06,-1.581805e+06,-4.481002e+06,-4.360537e+06,-4.898398e+06,-5.296679e+06,-5.558971e+06,-6.172605e+06,-5.903789e+06,-4.728435e+06,-4.284969e+06,-3.676702e+06,-4.024123e+06,-3.807250e+06,-3.795574e+06,-3.770703e+06,-3.775177e+06,-3.582934e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28301,1.090724e+07,1.105001e+07,1.218669e+07,1.733239e+07,1.779542e+07,2.535181e+07,2.598501e+07,5.068141e+07,5.585269e+07,7.262172e+07,7.586945e+07,6.748975e+07,5.839399e+07,4.334538e+07,8.244653e+07,4.659961e+07,5.259947e+07,1.154622e+08,9.240911e+07,8.109830e+07,1.102779e+08,9.277690e+07,4.983734e+07,4.328441e+07,5.777134e+07,1.275060e+08,6.845956e+07,102161459.2,1.058499e+08,7.926194e+07,1.106830e+08,7.183610e+07,6.891674e+07,7.492917e+07,1.306294e+08,1.189116e+08,1.145216e+08,1.096686e+08,9.604710e+07,9.052141e+07,5.871385e+07,1.436001e+08,1.090948e+08,2.783202e+07,3.927479e+07,6.356022e+07,3.578990e+07,5.695696e+07,8.169762e+07,7.601271e+07,9.395945e+07,1.110462e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19621,NaN,NaN,NaN,NaN,NaN,NaN,1.013200e+07,3.091841e+07,3.118078e+07,3.685336e+07,2.300690e+07,3.656406e+07,3.869021e+07,4.507738e+07,5.563774e+07,8.145406e+07,1.529467e+08,2.814554e+08,3.526296e+08,3.970550e+08,4.071932e+08,3.890067e+08,3.603105e+08,3.034220e+08,3.833955e+08,5.004126e+08,4.890082e+08,515371698.0,6.306721e+08,7.425764e+08,7.286726e+08,9.031666e+08,5.544451e+08,5.641260e+08,5.394004e+08,4.738433e+08,4.938727e+08,4.848211e+08,5.087489e+08,6.734427e+08,6.176871e+08,8.554935e+08,7.785791e+08,9.661594e+08,1.293255e+09,1.238595e+09,1.279933e+09,1.605888e+09,2.569882e+09,4.588783e+09,7.725612e+09,6.416573e+09,6.616324e+09,5.554376e+09,4.886702e+09,4.090140e+09,3.706266e+09,3.449590e+09,3.323652e+09,3.214145e+09

In [62]:
num = num.fillna(0)

In [63]:
num.head()

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.2500,8.0833,9.9575,0.0,7.8333,0.0,0.0,0.0,29.8333,0.0,0.0,19.8356,0.0,17.9041,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.2500,8.0833,9.9575,0.0,7.8333,0.0,0.0,0.0,29.8333,0.0,0.0,19.8356,0.0,17.9041,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.6176,43.0248,58.0061,0.0,21.2119,0.0,0.0,0.0,81.9289,0.0,0.0,64.2646,0.0,73.0790,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.6176,43.0248,58.0061,0.0,21.2119,0.0,0.0,0.0,81.9289,0.0,0.0,64.2646,0.0,73.0790,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [64]:
num.tail()

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
76815,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76816,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76817,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76818,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76819,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [65]:
num.sample(10)

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
6617,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.913476e+06,1.605038e+07,9.077868e+06,8.682392e+06,9.167217e+06,7.134163e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66731,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.800000e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.181468e+06,9.725117e+05,4.301832e+05,1.843717e+05,0.000000e+00,0.000000e+00,0.000000e+00,4.345528e+06,0.000000e+00,0.000000e+00,8.924190e+06,3.545773e+05,9.707140e+06,2.621946e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75398,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.100000e+04,5.800000e+04,5.000000e+04,1.500000e+04,4.000000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2410,3.291000e+09,3.415079e+09,3.593228e+09,3.621662e+09,4.029364e+09,4.002420e+09,4.926102e+09,5.248722e+09,5.676382e+09,9.567700e+09,1.241722e+10,1.843742e+10,1.802351e+10,3.000611e+10,3.096369e+10,3.508013e+10,3.734487e+10,4.189433e+10,4.128057e+10,3.393079e+10,2.816704e+10,2.789872e+10,2.755889e+10,2.551947e+10,3.328791e+10,3.652134e+10,3.919708e+10,4.553660e+10,5.418735e+10,5.720698e+10,5.362830e+10,5.772587e+10,5.433449e+10,5.348841e+10,4.848871e+10,4.693834e+10,4.642613e+10,4.924382e+10,5.521930e+10,5.634757e+10,5.797654e+10,6.264426e+10,6.030267e+10,6.102206e+10,6.179231e+10,6.492144e+10,5.667818e+10,7.035325e+10,7.380117e+10,7.456207e+10,7.424916e+10,6.900758e+10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20217,5.592932e+07,6.143658e+07,6.604015e+07,7.043030e+07,8.892135e+07,1.174338e+08,1.734276e+08,2.198353e+08,2.687324e+08,3.141567e+08,3.814978e+08,4.075203e+08,4.425056e+08,4.184099e+08,3.806783e+08,3.781278e+08,4.364451e+08,5.112921e+08,4.856503e+08,4.692364e+08,5.050142e+08,5.566626e+08,5.900160e+08,6.701868e+08,7.219769e+08,7.595005e+08,8.402343e+08,7.898395e+08,7.982243e+08,7.933347e+08,7.396575e+08,6.806183e+08,6.411194e+08,6.090982e+08,6.530079e+08,5.407891e+08,4.898524e+08,5.518761e+08,5.276970e+08,4.818779e+08,4.961208e+08,4.589157e+08,4.549656e+08,3.457325e+08,3.056671e+08,2.735448e+08,2.401444e+08,2.744196e+08,2.831214e+08,3.356631e+08,4.801465e+08,5.848584e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19637,-4.295000e+06,2.558000e+06,1.434400e+07,1.296500e+07,4.105200e+07,1.122180e+08,1.169400e+08,7.605500e+07,8.891500e+07,9.713300e+07,1.386060e+08,2.053120e+08,7.828100e+07,1.132230e+08,3.034700e+07,-6.657100e+07,-2.545600e+08,-3.895940e+08,-4.649630e+08,-2.760790e+08,-2.496160e+08,-4.931750e+08,-2.718700e+08,-2.662830e+08,-2.977860e+08,-2.033690e+08,-3.623600e+07,-1.641590e+08,-1.538470e+08,-2.860760e+08,-3.149740e+08,-2.588480e+08,-5.100840e+08,-2.678720e+08,-2.337530e+08,-2.575050e+08,-1.865610e+08,-2.147630e+08,-2.274590e+08,-1.499510e+08,-1.657790e+08,-1.130880e+08,-1.135440e+08,-1.145900e+08,-1.029460e+08,-3.985900e+07,2.132000e+06,1.470000e+07,4.453000e+06,2.297220e+08,3.365290e+08,-2.866100e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20320,2.277407e+06,2.711665e+06,4.933180e+06,9.107948e+06,9.182503e+06,9.306553e+06,1.413777e+07,2.937757e+07,7.884982e+07,1.290493e+08,1.986315e+08,3.040252e+08,3.934263e+08,2.729267e+08,7.205186e+08,5.920453e+08,5.401571e+08,1.208288e+08,1.020123e+08,1.799913e+08,1.915540e+08,2.280639e+08,1.297798e+08,7.323462e+07,1.465876e+08,4.602875e+08,4.847568e+08,5.588161e+08,7.035236e+08,6.041408e+08,7.651756e+08,5.777664e+08,5.093989e+08,4.525083e+08,4.816910e+08,5.202790e+08,6.223580e+08,6.054680e+08,4.694850e+08,1.722770e+08,8.295800e+07,8.020400e+07,7.781500e+07,8.039800e+07,2.053083e+08,4.297677e+08,4.650864e+08,9.654616e+08,1.410968e+09,1.504568e+09,4.149414e+08,1.281386e+08,761329827.1,756205031.5,752325501.1,748034824.9,724324724.4,678123061.4,631923398.4,585723000.6
37139,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44951,2.963700e+00,1.136240e+01,2.410000e+00,8.667200e+00,1.465440e+01,7.243600e+00,4.236800e+00,6.058300e+00,7.625000e+00,5.685100e+00,9.098700e+00,5.482300e+00,6.732100e+00,5.077600e+00,9.887900e+00,7.324400e+00,8.544500e+00,8.761600e+00,9.824700e+00,7.564500e+00,8.542200e+00,7.555000e+00,8.167600e+00,8.027100e+00,7.520600e+00,9.671600e+00,6.070400e+00,6.413200e+00,6.482100e+00,9.711400e+00,7.546600e+00,9.270000e+00,7.251400e+00,7.666900e+00,7.617600e+00,5.364200e+00,8.274300e+00,5.642500e+00,6.224400e+00,4.395100e+00,5.782200e+00,6.615200e+00,6.141100e+00,7.249400e+00,7.433800e+00,6.452200e+00,5.436100e+00,6.437700e+00,4.423100e+00,6.804800e+00,7.264300e+00,7.215900e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23504,7.233000e+06,4.922000e+06,3.796000e+06,3.010000e+06,1.332700e+07,1.673100e+07,1.981200e+07,1.770200e+07,7.428000e+06,1.826000e+06,-8.630000e+05,-1.233000e+06,-1.656000e+06,-2.596000e+06,-2.946000e+06,-3.541000e+06,-3.902000e+06,-3.655000e+06,-3.715000e+06,-4.614000e+06,-4.184000e+06,2.126648e+08,-3.205000e+06,4.276800e+07,1.121480e+08,3.665750e+08,4.862218e+08,4.534211e+08,4.705612e+08,5.525496e+08,3.983139e+08,2.353464e+08,6.522711e+08,5.438232e+08,8.257754e+08,4.714750e+08,4.752883e+08,4.927156e+08,5.415263e+08,7.937361e+08,5.771326e+08,4.432127e+08,3.276487e+08,6.902106e+05,1.306752e+08,3.481166e+08,-7.353040e+07,5.179137e+08,3.830071e+08,-3.589537e+08,1.601769e+09,1.488950e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [66]:

data.tail()

,Country Name,Country Code,Series Name,Series Code
76815,NaN,NaN,NaN,NaN
76816,NaN,NaN,NaN,NaN
76817,NaN,NaN,NaN,NaN
76818,Data from database: International Debt Statistics,NaN,NaN,NaN
76819,Last Updated: 12/06/2022,NaN,NaN,NaN

In [72]:
data['total'] = num.sum(axis=1)

<ipython-input-72-6701a6d2f639>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['total'] = num.sum(axis=1)

In [73]:
data.head()

,Country Name,Country Code,Series Name,Series Code,total
0,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.DPPG,103.6971
1,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.OFFT,103.6971
2,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.PRVT,0.0000
3,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.DPPG,392.1329
4,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.OFFT,392.1329

In [74]:
data.tail()

,Country Name,Country Code,Series Name,Series Code,total
76815,NaN,NaN,NaN,NaN,0.0
76816,NaN,NaN,NaN,NaN,0.0
76817,NaN,NaN,NaN,NaN,0.0
76818,Data from database: International Debt Statistics,NaN,NaN,NaN,0.0
76819,Last Updated: 12/06/2022,NaN,NaN,NaN,0.0

In [75]:
data.sample(10)

,Country Name,Country Code,Series Name,Series Code,total
52278,Nicaragua,NIC,"PS, bilateral concessional (AMT, current US$)",DT.AMT.BLTC.PS.CD,5.920146e+07
48842,Mongolia,MNG,"PRVG, official creditors (TDS, current US$)",DT.TDS.OFFT.PRVG.CD,0.000000e+00
41990,Low income,LIC,"PRVG, commercial banks (INT, current US$)",DT.INT.PCBK.PRVG.CD,9.218847e+06
27629,Guatemala,GTM,"OPS, private creditors (INT, current US$)",DT.INT.PRVT.OPS.CD,2.403900e+07
2199,Angola,AGO,"PS, bilateral (AMT, current US$)",DT.AMT.BLAT.PS.CD,2.285196e+10
69851,Tonga,TON,"PRVG, bilateral (NFL, current US$)",DT.NFL.BLAT.PRVG.CD,0.000000e+00
39810,Lebanon,LBN,"PS, private creditors (DIS, current US$)",DT.DIS.PRVT.PS.CD,7.353517e+10
62141,South Africa,ZAF,External debt stocks (% of GNI),DT.DOD.DECT.GN.ZS,7.989065e+02
2091,Angola,AGO,"PPG, multilateral concessional (INT, current US$)",DT.INT.MLTC.CD,7.702244e+07
66479,Syrian Arab Republic,SYR,"PRVG, official creditors (NFL, current US$)",DT.NFL.OFFT.PRVG.CD,0.000000e+00

In [76]:
data['total'] = data['total'].apply(lambda x: '{:,.0f}'.format(x))

<ipython-input-76-fd3db9794f88>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['total'] = data['total'].apply(lambda x: '{:,.0f}'.format(x))

In [77]:
data.head()

,Country Name,Country Code,Series Name,Series Code,total
0,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.DPPG,104
1,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.OFFT,104
2,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.PRVT,0
3,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.DPPG,392
4,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.OFFT,392

In [78]:
data.tail()

,Country Name,Country Code,Series Name,Series Code,total
76815,NaN,NaN,NaN,NaN,0
76816,NaN,NaN,NaN,NaN,0
76817,NaN,NaN,NaN,NaN,0
76818,Data from database: International Debt Statistics,NaN,NaN,NaN,0
76819,Last Updated: 12/06/2022,NaN,NaN,NaN,0

In [79]:
data.sample(10)

,Country Name,Country Code,Series Name,Series Code,total
66363,Syrian Arab Republic,SYR,"PPG, commercial banks (DOD, current US$)",DT.DOD.PCBK.CD,"193,237,677"
41105,Low & middle income,LMY,"GG, bilateral (DIS, current US$)",DT.DIS.BLAT.GG.CD,"852,406,155,710"
73714,Uzbekistan,UZB,"OPS, other private creditors (TDS, current US$)",DT.TDS.PROP.OPS.CD,"3,269,916,393"
47254,Middle income,MIC,"CB, bonds (DIS, current US$)",DT.DIS.PBND.CB.CD,"17,341,691,510"
55966,Peru,PER,"IMF purchases (DIS, current US$)",DT.DIS.DIMF.CD,"2,544,668,184"
9280,Bulgaria,BGR,"GG, multilateral concessional (NTR, current US$)",DT.NTR.MLTC.GG.CD,"299,315,951"
18921,Dominican Republic,DOM,"GG, bilateral concessional (DIS, current US$)",DT.DIS.BLTC.GG.CD,"5,045,119,895"
46433,Mexico,MEX,"PPG, bilateral concessional (DIS, current US$)",DT.DIS.BLTC.CD,"1,024,178,899"
10452,Burundi,BDI,"Interest arrears, private creditors (current US$)",DT.IXA.PRVT.CD,"1,546,128"
43399,Malawi,MWI,"GG, bonds (NTR, current US$)",DT.NTR.PBND.GG.CD,"-20,303,113"

In [82]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76820 entries, 0 to 76819
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  76817 non-null  object
 1   Country Code  76815 non-null  object
 2   Series Name   76815 non-null  object
 3   Series Code   76815 non-null  object
 4   total         76820 non-null  object
dtypes: object(5)
memory usage: 2.9+ MB

In [83]:
data['total'] = data['total'].str.replace(',','').astype('float64')

<ipython-input-83-601be5c5e4e8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['total'] = data['total'].str.replace(',','').astype('float64')

In [84]:
data.head()

,Country Name,Country Code,Series Name,Series Code,total
0,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.DPPG,104.0
1,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.OFFT,104.0
2,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.PRVT,0.0
3,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.DPPG,392.0
4,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.OFFT,392.0

In [85]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76820 entries, 0 to 76819
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  76817 non-null  object
 1   Country Code  76815 non-null  object
 2   Series Name   76815 non-null  object
 3   Series Code   76815 non-null  object
 4   total         76820 non-null  float64
dtypes: float64(1), object(4)
memory usage: 2.9+ MB